# Generated by Django 4.0.3 on 2022-06-14 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_expense', models.BooleanField(default=True, verbose_name='Расход?')),
                ('category', models.CharField(choices=[('donation', 'Плазмосдача'), ('salary', 'Зарплата'), ('mts_piggybank', 'Копилка МТС'), ('other', 'Прочее'), ('medicines', 'Лекарства'), ('rent', 'Аренда'), ('food', 'Еда'), ('phone', 'Телефон'), ('clothes', 'Одежда'), ('subscriptions', 'Подписки, донаты и т.д.'), ('household goods', 'Товары для быта и гигиены'), ('transport', 'Транспорт')], max_length=100, verbose_name='Категория')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
            ],
            options={
                'ordering': ('-date', 'is_expense'),
            },
        ),
    ]
